name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - id: cores
        name: refresh Arduino cores
        run: |
          echo 'https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://espressif.github.io/arduino-esp32/package_esp32_index.json,https://adafruit.github.io/arduino-board-index/package_adafruit_index.json' > ~/arduino-cores.txt
          arduino-cli version
          arduino-cli update --additional-urls "$(<~/arduino-cores.txt)"
          echo ::set-output name=d::$(sha256sum ~/.arduino15/package_*index.json | sha256sum | cut -d' ' -f1)
      - name: cache Arduino cores
        uses: actions/cache@v2
        with:
          path: ~/.arduino15/staging/packages
          key: cores-${{ steps.cores.outputs.d }}
      - name: install Arduino cores
        run: |
          arduino-cli core install arduino:avr esp8266:esp8266 esp32:esp32 adafruit:nrf52 --additional-urls "$(<~/arduino-cores.txt)"
          arduino-cli lib install Streaming
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          pip install adafruit-nrfutil esptool
          sudo apt-get install clang-format-11
      - uses: actions/checkout@v2
      - name: check code style
        run: |
          mk/format-code.sh
          git diff --exit-code
      - name: prepare Arduino libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE $HOME/Arduino/libraries/PriUint64
      - name: compile examples
        run: |
          for B in arduino:avr:uno esp8266:esp8266:nodemcuv2 esp32:esp32:esp32wrover adafruit:nrf52:feather52832; do
            for E in $(find ./examples -name '*.ino' -printf '%h\n'); do
              printf "\n----\033[1;35m Build %s in %s \033[0m----\n" ${E##*/} $B
              arduino-cli compile -b $B $E
            done
          done
